title: Alluxio Enterprise Properties Analysis
description: Code-based analysis of Alluxio Enterprise configuration properties.
theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - _data
